# Homebrew formulae, casks, and Mac App Store apps for this laptop.
# Installed (idempotently) by `brew bundle`, driven by roles/laptop/tasks/packages.yml.
# `brew bundle` handles its own ordering (taps -> brews -> casks -> mas).

tap "cirruslabs/cli"
tap "gitlab/shared-runners", "https://gitlab.com/gitlab-org/ci-cd/shared-runners/homebrew.git"

brew "ansible"
brew "aws-vault"
brew "awscli"
brew "btop"
brew "cirruslabs/cli/tart"
brew "coreutils"
brew "curl"
brew "direnv"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "esphome"
brew "exiftool"
brew "ffmpeg"
brew "findutils"
brew "gh"
brew "git"
brew "git-lfs"
brew "gitlab/shared-runners/sshpass"
brew "glab"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "grep"
brew "htop"
brew "imagemagick"
brew "mas"
brew "minicom"
brew "minipro"
brew "mise"
brew "moreutils"
brew "mosh"
brew "ncdu"
brew "nnn"
brew "pandoc"
brew "parallel"
brew "pinentry-mac"
brew "platformio"
brew "podman"
brew "pv"
brew "qemu"
brew "qrencode"
brew "rsync"
brew "scw"
brew "shellcheck"
brew "socat"
brew "stow"
brew "tig"
brew "trash"
brew "tree"
brew "typst"
brew "vim"
brew "virt-manager"
brew "wakeonlan"
brew "watch"
brew "wget"
brew "wireguard-tools"
brew "wireshark"
brew "xorriso"
brew "yt-dlp"

cask "1password"
cask "1password-cli"
cask "aegisub"
cask "alt-tab"
cask "arq"
cask "calibre"
cask "dash"
cask "db-browser-for-sqlite"
cask "diffmerge"
cask "digital"
cask "elgato-wave-link"
cask "firefox@developer-edition"
cask "flux-app"
cask "font-meslo-lg-nerd-font"
cask "gcloud-cli"
cask "gnucash"
cask "google-chrome"
cask "hex-fiend"
cask "istat-menus"
cask "key-codes"
cask "kicad"
cask "losslesscut"
cask "monero-wallet"
cask "musicbrainz-picard"
cask "omnidisksweeper"
cask "podman-desktop"
cask "portfolioperformance"
cask "screenflow"
cask "spotify"
cask "steam"
cask "superduper"
cask "superkey"
cask "telegram"
cask "the-unarchiver"
cask "transmission"
cask "utm"
cask "vagrant"
cask "vagrant-vmware-utility"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "windows-app"
cask "zoom"

# App Store apps need an interactive Apple ID sign-in, which can't be automated
# in the headless test VM, so skip them when HOMEBREW_LAPTOP_VM is set (see
# packages.yml, which bridges LAPTOP_VM -> HOMEBREW_LAPTOP_VM; Homebrew scrubs
# non-HOMEBREW_* vars from the Brewfile's environment). The Brewfile is Ruby, so
# this is a plain conditional; .to_s.empty? treats unset and empty as "not a VM".
if ENV["HOMEBREW_LAPTOP_VM"].to_s.empty?
  mas "Amphetamine", id: 937984704
  mas "Discovery", id: 1381004916
  mas "Divvy", id: 413857545
  mas "Final Cut Pro", id: 424389933
  mas "Merlin Project", id: 1335639877
  mas "Pixelmator Pro", id: 1289583905
  mas "uBlock Origin Lite", id: 6745342698
  mas "WiFi Explorer Lite", id: 1408727408
  mas "WiFi Signal", id: 525912054
  mas "WireGuard", id: 1451685025
end
