---

- name: go | Install go
  homebrew:
    name: go
  tags:
    - packages
    - go

- name: go | Ensure GOPATH directory is present
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gopath }}"
    - "{{ gopath }}/bin"
    - "{{ gopath }}/pkg"
    - "{{ gopath }}/src"
  tags:
    - packages
    - go

- name: go | Setup GOPATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export GOPATH="{{ gopath }}"'
    regexp: '^export GOPATH'
  tags:
    - packages
    - go

- name: go | Add go binaries to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="$GOPATH/bin:$PATH"'
  tags:
    - packages
    - go

- name: go | Setup GOROOT
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export GOROOT="/usr/local/opt/go/libexec/bin"'
  tags:
    - packages
    - go

- name: go | Install gin
  shell: "GOPATH={{ gopath }} go get github.com/codegangsta/gin"
  args:
    creates: "{{ gopath }}/src/github.com/codegangsta/gin"
  tags:
    - packages
    - go

- name: go | Install godep
  shell: "GOPATH={{ gopath }} go get github.com/tools/godep"
  args:
    creates: "{{ gopath }}/src/github.com/tools/godep"
  tags:
    - packages
    - go

- name: go | Install goimports
  shell: "GOPATH={{ gopath }} go get go golang.org/x/tools/cmd/goimports"
  args:
    creates: "{{ gopath }}/src/golang.org/x/tools/cmd/goimports"
  tags:
    - packages
    - go

