---

- name: Install vagrant
  homebrew_cask:
    name: vagrant
  tags:
    - vagrant

- name: Install parallels-virtualization-sdk
  homebrew_cask:
    name: parallels-virtualization-sdk
  tags:
    - vagrant

- name: Install vagrant plugins
  shell: "/usr/local/bin/vagrant plugin list | grep -q {{ item }} || /usr/local/bin/vagrant plugin install {{ item }}"
  with_items:
    - vagrant-cachier
    - vagrant-parallels
    - vagrant-fsnotify
  register: _vagrant_plugin
  changed_when: "'Installing' in _vagrant_plugin.stdout"
  tags:
    - vagrant

- name: Add vagrant to sudoers
  lineinfile:
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    dest: /etc/sudoers
  sudo: true
  with_items:
    - line: "# Allow passwordless startup of Vagrant when using NFS."
      regexp: "^# Allow passwordless"
    - line: Cmnd_Alias VAGRANT_EXPORTS_ADD_SHR = /usr/bin/tee -a /etc/exports
      regexp: "^Cmnd_Alias VAGRANT_EXPORTS_ADD_SHR"
    - line: Cmnd_Alias VAGRANT_EXPORTS_ADD_BREW = /usr/local/opt/coreutils/libexec/gnubin/tee -a /etc/exports
      regexp: "^Cmnd_Alias VAGRANT_EXPORTS_ADD_BREW"
    - line: Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
      regexp: "^Cmnd_Alias VAGRANT_NFSD"
    - line: Cmnd_Alias VAGRANT_EXPORTS_REMOVE_SHR = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
      regexp: "^Cmnd_Alias VAGRANT_EXPORTS_REMOVE_SHR"
    - line: Cmnd_Alias VAGRANT_EXPORTS_REMOVE_BREW = /usr/local/opt/gnu-sed/libexec/gnubin/sed -E -e /*/ d -ibak /etc/exports
      regexp: "^Cmnd_Alias VAGRANT_EXPORTS_REMOVE_BREW"
    - line: "%staff ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD_SHR, VAGRANT_EXPORTS_ADD_BREW, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE_SHR, VAGRANT_EXPORTS_REMOVE_BREW"
      regexp: "^%staff ALL=(root) NOPASSWD: VAGRANT"
  tags:
    - vagrant
