---

- name: Install vagrant
  homebrew_cask:
    name: vagrant
  tags:
    - vagrant

- name: Install parallels-virtualization-sdk
  homebrew_cask:
    name: parallels-virtualization-sdk
  tags:
    - vagrant

- name: Install virtualbox
  homebrew_cask:
    name: virtualbox
  tags:
    - vagrant

# todo : make it indepotent
- name: Install vagrant plugins
  shell: "/usr/bin/vagrant plugin list | grep -q {{ item }} || /usr/bin/vagrant plugin install {{ item }}"
  with_items:
    - vagrant-cachier
    - vagrant-bindfs
    - vagrant-parallels
  register: _vagrant_plugin
  changed_when: "'Installing' in _vagrant_plugin.stdout"
  tags:
    - vagrant
