---

- name: Fetch Homebrew installer
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew-install.sh
  tags:
    - base

- name: Install Homebrew
  command: /tmp/homebrew-install.sh
  args:
    creates: "/usr/local/Homebrew/.git"
  tags:
    - base

- name: Update homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - base
