---

- name: Ensure configured taps are tapped.
  homebrew_tap:
    tap: gitlab/shared-runners
    url: https://gitlab.com/gitlab-org/ci-cd/shared-runners/homebrew.git
    state: present

- name: Install brew packages
  homebrew:
    name:
      - awscli
      - ansible
      - coreutils
      - exiftool
      - ffmpeg
      - findutils
      - fzf
      - git
      - gitlab/shared-runners/sshpass
      - gnu-sed
      - gnu-tar
      - gnupg
      - grep
      - htop
      - jq
      - kubernetes-helm
      - minipro
      - moreutils
      - pinentry-mac
      - shellcheck
      - socat
      - tig
      - trash
      - tree
      - vim
      - watch
      - wget
      - youtube-dl
      - zsh-autosuggestions
      - zsh-syntax-highlighting
  tags:
    - packages

- name: Install FZF
  shell: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
  args:
    creates: "{{ ansible_user_dir }}/.fzf.zsh"
  tags:
    - packages
