---

- name: Ensure configured taps are tapped.
  homebrew_tap:
    tap: gitlab/shared-runners
    url: https://gitlab.com/gitlab-org/ci-cd/shared-runners/homebrew.git
    state: present

- name: Install brew packages
  homebrew:
    name:
      - ansible
      - aws-vault
      - awscli
      - btop
      - cmake
      - colima
      - coreutils
      - curl
      - direnv
      - docker
      - exiftool
      - ffmpeg
      - findutils
      - gh
      - git
      - git-lfs
      - gitlab/shared-runners/sshpass
      - glab
      - gnu-sed
      - gnu-tar
      - gnupg
      - grep
      - htop
      - imagemagick
      - minipro
      - mise
      - moreutils
      - mosh
      - ncdu
      - nnn
      - pandoc
      - parallel
      - pinentry-mac
      - platformio
      - pv
      - rsync
      - shellcheck
      - socat
      - stow
      - tig
      - trash
      - tree
      - vim
      - wakeonlan
      - watch
      - wget
      - yt-dlp
  tags:
    - packages
