---

- name: Ensure configured taps are tapped.
  homebrew_tap:
    tap: gitlab/shared-runners
    url: https://gitlab.com/gitlab-org/ci-cd/shared-runners/homebrew.git
    state: present

- name: Install brew packages
  homebrew:
    name:
      - awscli
      - ansible
      - colima
      - coreutils
      - docker
      - exiftool
      - ffmpeg
      - findutils
      - git
      - gitlab/shared-runners/sshpass
      - gnu-sed
      - gnu-tar
      - gnupg
      - grep
      - htop
      - jq
      - minipro
      - mise
      - moreutils
      - nnn
      - pinentry-mac
      - platformio
      - rsync
      - shellcheck
      - socat
      - stow
      - tig
      - trash
      - tree
      - vim
      - watch
      - wakeonlan
      - wget
      - youtube-dl
  tags:
    - packages
