---

- name: Taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - homebrew/cask-drivers
    - homebrew/cask-fonts
    - homebrew/cask-versions
  tags:
    - casks

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - 1password
    - 1password-cli
    - adobe-creative-cloud
    - aerial
    - arq
    - aws-vault
    - bonjour-browser
    - calibre
    - charles
    - dash
    - db-browser-for-sqlite
    - diffmerge
    - encryptme
    - flux
    - font-anonymous-pro
    - font-meslo-lg
    - font-roboto
    - gnucash
    - google-chrome-beta
    - google-cloud-sdk
    # - houdahgeo
    - imagealpha
    - imageoptim
    - istat-menus
    - intel-power-gadget
    - iterm2
    - java8
    - logitech-options
    - logitech-unifying
    - musicbrainz-picard
    - ngrok
    - omnidisksweeper
    - pgadmin4
    - skype
    - slack
    - sonos
    - soundflower
    - spotify
    - steam
    - sublime-text
    - superduper
    - telegram-desktop
    - the-unarchiver
    - transmission
    - vagrant
    - vagrant-vmware-utility
    - virtualbox
    - viscosity
    - visual-studio-code
    - vlc
    - vmware-fusion10
    - xquartz
  tags:
    - casks

- name: java | Setup JAVA_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
  tags:
    - casks

- name: adobe-creative-cloud | run installer
  shell: open '/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app'
  args:
    creates: /Applications/Adobe Creative Cloud
  tags:
    - casks
