---

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - 1password
    - 1password-cli
    - arq
    - calibre
    - dash
    - db-browser-for-sqlite
    - diffmerge
    - elgato-wave-link
    - firefox@developer-edition
    - flux-app
    - gcloud-cli
    - gnucash
    - google-chrome
    - hex-fiend
    - istat-menus
    - losslesscut
    - musicbrainz-picard
    - omnidisksweeper
    - portfolioperformance
    - screenflow
    - slack
    - sonos
    - spotify
    - steam
    - superduper
    - telegram
    - the-unarchiver
    - transmission
    - visual-studio-code
    - vlc
    - whatsapp
    - zoom
  tags:
    - casks
