---

- name: Taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - adrienkohlbecker/own
    - caskroom/drivers
    - caskroom/fonts
    - caskroom/versions
  tags:
    - casks

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - adobe-creative-cloud
    - android-studio
    - arq
    - aws-vault
    - caprine
    - charles
    - dash
    - diffmerge
    - docker
    - dropbox
    - flux
    - font-anonymous-pro
    - font-meslo-lg
    - font-roboto
    - gnucash
    - google-chrome-beta
    - google-drive
    - houdahgeo
    - imagealpha
    - imageoptim
    - istat-menus
    - iterm2
    - java7
    - lastfm
    - logitech-options
    - logitech-unifying
    - musicbrainz-picard
    - ngrok
    - omnidisksweeper
    - parallels-virtualization-sdk
    - paw
    - pgadmin4
    - skype
    - slack
    - sonos
    - spotify
    - sqlitebrowser
    - steam
    - sublime-text
    - superduper
    - telegram-desktop
    - the-unarchiver
    - transmission
    - vagrant
    - virtualbox
    - viscosity
    - visual-studio-code
    - vlc
    - xquartz
  tags:
    - casks

- name: java | Setup JAVA_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export JAVA_HOME="$(/usr/libexec/java_home -v 1.7)"
  tags:
    - casks

- name: android-studio | Setup ANDROID_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export ANDROID_HOME="$HOME/Library/Android/sdk"
  tags:
    - casks

- name: android-studio | Setup PATH for Android SDK
  lineinfile:
    dest: ~/.zshrc.local
    line: export PATH="$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/platform-tools:$HOME/Library/Android/sdk/build-tools:$PATH"
  tags:
    - casks
