---

- name: Taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items:
    - homebrew/cask-drivers
    - homebrew/cask-versions
  tags:
    - casks

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - homebrew/cask/1password
    - homebrew/cask/1password-cli
    - homebrew/cask/divvy
    - homebrew/cask/arq
    - homebrew/cask/aws-vault
    - homebrew/cask/calibre
    - homebrew/cask/dash
    - homebrew/cask/db-browser-for-sqlite
    - homebrew/cask/diffmerge
    - homebrew/cask-versions/firefox-developer-edition
    - homebrew/cask/docker
    - homebrew/cask/flux
    - homebrew/cask/gnucash
    - homebrew/cask-versions/google-chrome-beta
    - homebrew/cask/google-cloud-sdk
    - homebrew/cask/hex-fiend
    # - homebrew/cask/houdahgeo
    - homebrew/cask/istat-menus
    - homebrew/cask/intel-power-gadget
    - homebrew/cask-drivers/logitech-options
    - homebrew/cask/losslesscut
    - homebrew/cask/mailplane
    - homebrew/cask/musicbrainz-picard
    - homebrew/cask/omnidisksweeper
    - homebrew/cask/slack
    - homebrew/cask-drivers/sonos
    - homebrew/cask/spotify
    - homebrew/cask/steam
    - homebrew/cask/superduper
    - homebrew/cask/telegram
    - homebrew/cask/transmission
    - homebrew/cask/vagrant
    - homebrew/cask/vagrant-vmware-utility
    - homebrew/cask/virtualbox
    - homebrew/cask/visual-studio-code
    - homebrew/cask/vlc
    # - homebrew/cask/vmware-fusion12
  tags:
    - casks
