---

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - 1password
    - 1password-cli
    - aegisub
    - alt-tab
    - arq
    - calibre
    - dash
    - db-browser-for-sqlite
    - diffmerge
    - digital
    - elgato-wave-link
    - firefox@developer-edition
    - flux-app
    - font-meslo-lg-nerd-font
    - gcloud-cli
    - gnucash
    - google-chrome
    - hex-fiend
    - istat-menus
    - kicad
    - losslesscut
    - monero-wallet
    - musicbrainz-picard
    - omnidisksweeper
    - podman-desktop
    - portfolioperformance
    - screenflow
    - spotify
    - steam
    - superduper
    - superkey
    - telegram
    - the-unarchiver
    - transmission
    - vagrant
    - vagrant-vmware-utility
    - visual-studio-code
    - vlc
    - whatsapp
    - zoom
  tags:
    - casks
