---

- import_tasks: packages.yml
  tags:
    - packages

- import_tasks: stow.yml
  tags:
    - stow

- import_tasks: mise.yml
  tags:
    - mise

- import_tasks: settings.yml
  tags:
    - settings
