---

- name: Install git
  homebrew:
    name:
      - git
      - findutils
      - grep
      - gnu-sed
      - gnu-tar
  tags:
    - packages

- name: Install packages
  homebrew_cask:
    name: osxfuse # depenency of sshfs
  tags:
    - packages

- name: Install packages
  homebrew:
    name:
      - aacgain
      - awscli
      - chruby
      - coreutils
      - dep
      - docker
      - docker-compose
      - docker-credential-helper
      - docker-machine
      - dockutil
      - dpkg
      - exiftool
      - ffmpeg
      - fzf
      - gnupg2
      - go
      - htop
      - hub
      - icdiff
      - imagemagick
      - jq
      - lego
      - libav # avconv
      - moreutils
      - mosh
      - mp3info
      - mp4v2
      - mp4box
      - nmap
      - node
      - openssl
      - packer
      - pinentry-mac
      - rclone
      - ruby-install
      - screen
      - shellcheck
      - socat
      - sound-touch # soundstretch
      - sshfs
      - telnet
      - tfenv
      - tmux
      - tig
      - trash
      - tree
      - vim
      - watch
      - wget
      - wireguard-go
      - wireguard-tools
      - youtube-dl
      - zsh-history-substring-search
      - zsh-syntax-highlighting
      - jansson # telegram-cli
      - libconfig # telegram-cli
  tags:
    - packages

- name: Start gpg-agent on login
  lineinfile:
    dest: ~/.zshrc.local
    line: 'gpg-agent --daemon'
  tags:
    - packages

- name: Enable aws completion
  lineinfile:
    dest: ~/.zshrc.local
    line: 'source /usr/local/share/zsh/site-functions/_aws'
  tags:
    - packages

- name: Add unprefixed findutils to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed grep to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed gnu-sed to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed gnu-tar to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed coreutils to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed coreutils to MANPATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"'
  tags:
    - packages
