---

- name: Install git
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.options }}"
  with_items:
    - name: git
      options:
        - with-blk-sha1 # Compile with the block-optimized SHA1 implementation (10% faster than openssl's)
    - name: findutils
      options:
        - with-default-names # Do not prepend 'g' to the binary
    - name: grep
      options:
        - with-default-names # Do not prepend 'g' to the binary
    - name: gnu-sed
      options:
        - with-default-names # Do not prepend 'g' to the binary
    - name: gnu-tar
      options:
        - with-default-names # Do not prepend 'g' to the binary
  tags:
    - packages

- name: Install packages
  homebrew_cask:
    name: osxfuse # depenency of sshfs
  tags:
    - packages

- name: Install packages
  homebrew:
    name: "{{ item }}"
  with_items:
    - aacgain
    - awscli
    - chruby
    - coreutils
    - dep
    - docker
    - docker-compose
    - docker-credential-helper
    - docker-machine
    - dockutil
    - dpkg
    - exiftool
    - ffmpeg
    - gnupg2
    - go
    - htop
    - hub
    - imagemagick
    - jq
    - lego
    - moreutils
    - mosh
    - mp3info
    - mp4v2
    - nmap
    - node
    - openssl
    - packer
    - pinentry-mac
    - rclone
    - ruby-install
    - screen
    - shellcheck
    - socat
    - sshfs
    - telnet
    - tfenv
    - tmux
    - tig
    - tree
    - vim
    - watch
    - wget
    - youtube-dl
    - zsh-history-substring-search
    - zsh-syntax-highlighting
  tags:
    - packages

- name: Start gpg-agent on login
  lineinfile:
    dest: ~/.zshrc.local
    line: 'gpg-agent --daemon'
  tags:
    - packages

- name: Enable aws completion
  lineinfile:
    dest: ~/.zshrc.local
    line: 'source /usr/local/share/zsh/site-functions/_aws'
  tags:
    - packages

- name: Add unprefixed coreutils to PATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"'
  tags:
    - packages

- name: Add unprefixed coreutils to MANPATH
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"'
  tags:
    - packages
