---

- name: ruby | Update rubygems
  shell: "/usr/local/opt/ruby/bin/gem update --system"
  changed_when: false
  tags:
    - ruby

- name: ruby | Install bundler
  gem:
    name: bundler
    executable: /usr/local/opt/ruby/bin/gem
  tags:
    - ruby

- name: ruby | Configure bundler parallelism
  shell: "mkdir -p $HOME/.bundle && echo \"---\\nBUNDLE_JOBS: '{{ ansible_processor_cores }}'\" > $HOME/.bundle/config"
  changed_when: false
  tags:
    - ruby

- name: ruby | Install packages
  gem:
    name: "{{ item }}"
    executable: /usr/local/opt/ruby/bin/gem
  with_items:
    - awesome_print
    - foreman
    - rubocop
    - rubocop-rspec
    - rubocop-rails
    - haml_lint
    - scss_lint
    - terraform_landscape
  tags:
    - ruby
