---

- name: Create ssh directory
  file:
    path: "~/.ssh"
    state: directory
    recurse: true
  tags:
    - settings

- name: Create ssh config.d directory
  file:
    path: "~/.ssh/config.d"
    state: directory
    recurse: true
  tags:
    - settings

- name: Copy using inline content
  copy:
    content: "Host *\n  UseKeychain yes\n"
    dest: "~/.ssh/config.d/keychain"
  tags:
    - settings

- name: Set cron env var
  cron:
    name: SHELL
    env: yes
    job: /bin/zsh
  tags:
    - settings
    - focus

- name: Enable compta cron
  cron:
    name: daily compta
    minute: "05"
    hour: "11"
    job: "cd {{ home }}/Work/compta && bin/daily &> daily.log && /opt/homebrew/opt/curl/bin/curl --request POST --location --fail --silent --show-error --connect-timeout 1 --max-time 5 -o /dev/null \"https://healthchecks.lab.fahm.fr/ping/4dcc7a44-e0c8-4a43-87a9-92eb09133e28\""
  tags:
    - settings

- name: Enable backup cron
  cron:
    name: weekly backup
    minute: "25"
    hour: "11"
    weekday: "1"
    user: root
    job: "cd {{ home }} && /usr/bin/python3 .backup.py &> .backup.log && /opt/homebrew/opt/curl/bin/curl --request POST --location --fail --silent --show-error --connect-timeout 1 --max-time 5 -o /dev/null \"https://healthchecks.lab.fahm.fr/ping/0bc911c1-f540-45c1-8e21-e58909519523\""
  become: true
  tags:
    - settings

- name: "Check for updates automatically"
  shell: softwareupdate --schedule on
  changed_when: false
  become: true
  tags:
    - settings

- name: "Show the ~/Library folder"
  shell: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings

- name: "Save screenshots to ~/Downloads"
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Downloads
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: KeyRepeat
    type: float
    value: 2
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: InitialKeyRepeat
    type: float
    value: 15
    state: present

- name: Set faster dock hide
  osx_defaults:
    domain: com.apple.Dock
    key: autohide-delay
    type: float
    value: 0
    state: present

- name: Disable popup when long-pressing accented keys like "e"
  osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present
