---

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_REGION="eu-west-1"'
  tags:
    - settings

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_DEFAULT_REGION="eu-west-1"'
  tags:
    - settings

- name: Create ssh directory
  file:
    path: "~/.ssh"
    state: directory
    recurse: true
  tags:
    - settings

- name: Create controlmasters directory
  file:
    path: "~/.ssh/controlmasters"
    state: directory
    recurse: true
  tags:
    - settings

- name: Enable compta cron
  cron:
    name: daily compta
    minute: "32"
    hour: "17"
    job: "{{ home }}/Desktop/compta/daily.sh 2>&1 | tee -a {{ home }}/Desktop/compta/log/daily.log"
  tags:
    - settings

- name: "Check for updates automatically"
  shell: softwareupdate --schedule on
  changed_when: false
  become: true
  tags:
    - settings

- name: "Show the ~/Library folder"
  shell: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings
