---

- name: Create ssh directory
  file:
    path: "~/.ssh"
    state: directory
    recurse: true
  tags:
    - settings

- name: Create controlmasters directory
  file:
    path: "~/.ssh/controlmasters"
    state: directory
    recurse: true
  tags:
    - settings

- name: Enable compta cron
  cron:
    name: daily compta
    minute: "32"
    hour: "17"
    job: "{{ home }}/Work/compta/daily.sh 2>&1 | tee -a {{ home }}/Work/compta/log/daily.log"
  tags:
    - settings

- name: "Check for updates automatically"
  shell: softwareupdate --schedule on
  changed_when: false
  become: true
  tags:
    - settings

- name: "Show the ~/Library folder"
  shell: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings

- name: "Save screenshots to ~/Downloads"
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Downloads
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present
