---

- name: Create ssh directory
  file:
    path: "~/.ssh"
    state: directory
    recurse: true
  tags:
    - settings

- name: Create controlmasters directory
  file:
    path: "~/.ssh/controlmasters"
    state: directory
    recurse: true
  tags:
    - settings

- name: Enable compta cron
  cron:
    name: daily compta
    minute: "32"
    hour: "22"
    job: "cd {{ home }}/Work/compta && bin/daily > daily.log 2>&1"
  tags:
    - settings

- name: "Check for updates automatically"
  shell: softwareupdate --schedule on
  changed_when: false
  become: true
  tags:
    - settings

- name: "Show the ~/Library folder"
  shell: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings

- name: "Save screenshots to ~/Downloads"
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Downloads
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: KeyRepeat
    type: float
    value: 2
    state: present

- name: Set faster key repeat
  osx_defaults:
    key: InitialKeyRepeat
    type: float
    value: 15
    state: present

- name: Set faster dock hide
  osx_defaults:
    domain: com.apple.Dock
    key: autohide-delay
    type: float
    value: 0
    state: present
