---

- name: Install google-chrome-beta
  homebrew_cask:
    name: google-chrome-beta
  tags:
    - apps
    - chrome

# Needed by karma-chrome-launcher
- name: Set CHROME_BIN
  lineinfile:
    line: export CHROME_BIN="/opt/homebrew-cask/Caskroom/google-chrome-beta/latest/Google Chrome.app/Contents/MacOS/Google Chrome"
    dest: ~/.zshrc.local
  tags:
    - apps
    - chrome

- name: Create chrome directory
  file:
    path: "~/Library/Google/Chrome/External Extensions/"
    state: directory
    recurse: true
  tags:
    - apps
    - chrome


- name: Setup chrome extensions
  copy:
    src: extension.json
    dest: "~/Library/Google/Chrome/External Extensions/{{ item }}.json"
  with_items:
    - hdokiejnpimakedhajhdlcegeplioahd # LastPass
    - fhbjgbiflinjbdggehcddcbncdddomop # Postman
    - aicmkgpgakddgnaphhhpliifpcfhicfo # Postman interceptor
    - jdbcdblgjdpmfninkoogcfpnkjmndgje # Scrum for trello
    - ogcgkffhplmphkaahpmffcafajaocjbd # Zenhub
    - oapdhhkmnfhbiciagepjminahingaiik # Zenhub points counter
  tags:
    - apps
    - chrome
