---


- name: iterm | Install iterm2-nightly
  homebrew_cask:
    name: iterm2
  tags:
    - apps
    - iterm

- name: iterm | Copy iterm settings
  copy:
    src: com.googlecode.iterm2.plist
    dest: ~/Library/Preferences/com.googlecode.iterm2.plist
  tags:
    - apps
    - iterm

- name: iterm | Reload iterm settings
  shell: defaults read com.googlecode.iterm2
  tags:
    - apps
    - iterm

- name: iterm | Open iterm
  shell: "open -a '{{ brew_cask_install_directory }}/iTerm.app'"
  changed_when: false
  tags:
    - apps
    - iterm
