---

- name: Tap caskroom/versions
  homebrew_tap:
    tap: caskroom/versions
  tags:
    - apps

- name: Install packages
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - adobe-creative-cloud
    - android-studio
    - atom
    - aws-vault
    - caprine
    - charles
    - diffmerge
    - docker
    - firefox-beta
    - gmvault
    - google-drive
    - google-play-music-desktop-player
    - gpgtools
    - imagealpha
    - imageoptim
    - istat-menus
    - java7
    - lastfm
    - logitech-options
    - logitech-unifying
    - musicbrainz-picard
    - ngrok
    - paw
    - pgadmin4
    - skype
    - slack
    - spotify
    - sqlitebrowser
    - sublime-text
    - telegram-desktop
    - the-unarchiver
    - transmission
    - virtualbox
    - viscosity
    - visual-studio-code
    - vlc
    - xquartz
  tags:
    - apps

- name: java | Setup JAVA_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export JAVA_HOME="$(/usr/libexec/java_home -v 1.7)"
  tags:
    - apps

- name: atom | Install atom plugins
  shell: apm install {{ item }}
  args:
    creates: "{{ home }}/.atom/packages/{{item}}"
  with_items:
    - Sublime-Style-Column-Selection
    - advanced-open-file
    - afterglow-like
    - afterglow-monokai-syntax
    - atom-jade
    - atom-typescript
    - color-picker
    - dash
    - editorconfig
    - file-icons
    - file-types
    - git-plus
    - go-debug
    - go-plus
    - highlight-selected
    - language-ansible
    - language-docker
    - language-gradle
    - language-haml
    - language-ini
    - language-pgsql
    - language-systemd
    - linter
    - linter-erb
    - linter-haml
    - linter-js-yaml
    - linter-jshint
    - linter-jsonlint
    - linter-pylama
    - linter-rubocop
    - linter-scss-lint
    - linter-shellcheck
    - linter-tslint
    - minimap
    - pigments
    - pretty-json
    - project-manager
    - sort-lines
    - tab-title
    - toggle-quotes
  tags:
    - apps

- name: android-studio | Setup ANDROID_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export ANDROID_HOME="$HOME/Library/Android/sdk"
  tags:
    - apps

- name: android-studio | Setup PATH for Android SDK
  lineinfile:
    dest: ~/.zshrc.local
    line: export PATH="$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/platform-tools:$HOME/Library/Android/sdk/build-tools:$PATH"
  tags:
    - apps

- name: Open apps
  shell: "open -a '{{ brew_cask_install_directory }}/{{ item }}.app'"
  changed_when: false
  with_items:
    - Sublime Text
    - The Unarchiver
    - Google Drive
  tags:
    - apps

- name: Open adobe installer
  shell: "open -a '/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app'"
  changed_when: false
  tags:
    - apps

- include: chrome.yml
- include: flux.yml
- include: iterm.yml
- include: mas.yml
