---

- name: Tap caskroom/versions
  homebrew_tap:
    tap: caskroom/versions
  tags:
    - apps

- name: Install java7
  homebrew_cask:
    name: java7
  tags:
    - apps

- name: Setup JAVA_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export JAVA_HOME="$(/usr/libexec/java_home -v 1.7)"
  tags:
    - apps

- name: Install skype
  homebrew_cask:
    name: skype
  tags:
    - apps

- name: Install sublime-text
  homebrew_cask:
    name: sublime-text
  tags:
    - apps

- name: Open Sublime Text
  shell: "open -a '{{ brew_cask_install_directory }}/Sublime Text.app'"
  changed_when: false
  tags:
    - apps

- name: Install atom
  homebrew_cask:
    name: atom
  tags:
    - apps

- name: Install atom plugins
  shell: apm install {{ item }}
  args:
    creates: "{{ home }}/.atom/packages/{{item}}"
  with_items:
    - Sublime-Style-Column-Selection
    - advanced-open-file
    - afterglow-like
    - afterglow-monokai-syntax
    - atom-jade
    - atom-typescript
    - color-picker
    - dash
    - editorconfig
    - file-icons
    - file-types
    - git-plus
    - go-debug
    - go-plus
    - highlight-selected
    - language-ansible
    - language-docker
    - language-gradle
    - language-haml
    - language-ini
    - language-pgsql
    - language-systemd
    - linter
    - linter-erb
    - linter-haml
    - linter-js-yaml
    - linter-jshint
    - linter-jsonlint
    - linter-pylama
    - linter-rubocop
    - linter-scss-lint
    - linter-shellcheck
    - linter-tslint
    - minimap
    - pigments
    - pretty-json
    - project-manager
    - sort-lines
    - tab-title
    - toggle-quotes
  tags:
    - apps

- name: Install diffmerge
  homebrew_cask:
    name: diffmerge
  tags:
    - apps

- name: Install google-drive
  homebrew_cask:
    name: google-drive
  tags:
    - apps

- name: Open Google Drive
  shell: "open -a '{{ brew_cask_install_directory }}/Google Drive.app'"
  changed_when: false
  tags:
    - apps

- name: Install android-studio
  homebrew_cask:
    name: android-studio
  tags:
    - apps

- name: Setup ANDROID_HOME
  lineinfile:
    dest: ~/.zshrc.local
    line: export ANDROID_HOME="$HOME/Library/Android/sdk"
  tags:
    - apps

- name: Setup PATH for Android SDK
  lineinfile:
    dest: ~/.zshrc.local
    line: export PATH="$HOME/Library/Android/sdk/tools:$HOME/Library/Android/sdk/platform-tools:$HOME/Library/Android/sdk/build-tools:$PATH"
  tags:
    - apps

- name: Install xquartz
  homebrew_cask:
    name: xquartz
  tags:
    - apps

- name: Install slack
  homebrew_cask:
    name: slack
  tags:
    - apps

- name: Install imagealpha
  homebrew_cask:
    name: imagealpha
  tags:
    - apps

- name: Install imageoptim
  homebrew_cask:
    name: imageoptim
  tags:
    - apps

- name: Install the-unarchiver
  homebrew_cask:
    name: the-unarchiver
  tags:
    - apps

- name: Install logitech-options
  homebrew_cask:
    name: logitech-options
  tags:
    - apps

- name: Install logitech-unifying
  homebrew_cask:
    name: logitech-unifying
  tags:
    - apps

- name: Open the-unarchiver
  shell: "open -a '{{ brew_cask_install_directory }}/The Unarchiver.app'"
  changed_when: false
  tags:
    - apps

- name: Install vlc
  homebrew_cask:
    name: vlc
  tags:
    - apps

- name: Install pgadmin4
  homebrew_cask:
    name: pgadmin4
  tags:
    - apps

- name: Install firefox-beta
  homebrew_cask:
    name: firefox-beta
  tags:
    - apps

- name: Install Paw
  homebrew_cask:
    name: paw
  tags:
    - apps

- name: Install ngrok
  homebrew_cask:
    name: ngrok
  tags:
    - apps

- name: Install charles
  homebrew_cask:
    name: charles
  tags:
    - apps

- name: Install viscosity
  homebrew_cask:
    name: viscosity
  tags:
    - apps

- name: Install transmission
  homebrew_cask:
    name: transmission
  tags:
    - apps

- name: Install sqlitebrowser
  homebrew_cask:
    name: sqlitebrowser
  tags:
    - apps

- name: Install caprine
  homebrew_cask:
    name: caprine
  tags:
    - apps

- name: Install musicbrainz-picard
  homebrew_cask:
    name: musicbrainz-picard
  tags:
    - apps

- name: Install gpgtools
  homebrew_cask:
    name: gpgtools
  tags:
    - apps

- name: Install telegram-desktop
  homebrew_cask:
    name: telegram-desktop
  tags:
    - apps

- name: Install docker
  homebrew_cask:
    name: docker
  tags:
    - apps

- name: Install spotify
  homebrew_cask:
    name: spotify
  tags:
    - apps

- name: Install lastfm
  homebrew_cask:
    name: lastfm
  tags:
    - apps

- name: Install google-play-music-desktop-player
  homebrew_cask:
    name: google-play-music-desktop-player
  tags:
    - apps

- name: Install lastfm
  homebrew_cask:
    name: lastfm
  tags:
    - apps

- include: chrome.yml
- include: flux.yml
- include: iterm.yml
- include: mas.yml
