---

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_REGION="eu-west-1"'
  tags:
    - sharette

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_DEFAULT_REGION="eu-west-1"'
  tags:
    - sharette

- name: Setup ssh_config
  template:
    src: ssh_config.j2
    dest: ~/.ssh/config
  tags:
    - sharette
