---

- name: Ensure sharette directory is present
  file:
    path: ~/Desktop/sharette
    state: directory
  tags:
    - sharette

- name: Ensure secure_files directory is present
  file:
    path: ~/Desktop/sharette
    state: directory
  tags:
    - sharette

- name: Ensure sublime project is present
  copy:
    src: sharette.sublime-project
    dest: ~/Desktop/sharette/sharette.sublime-project
  tags:
    - sharette

- name: Link sharette to GOPATH
  file:
    src: ~/Desktop/sharette
    path: "{{ gopath }}/src/github.com/sharette"
    state: link
  tags:
    - sharette

- name: Install dev box
  shell: "/usr/local/bin/vagrant box list | grep -q sharette || /usr/local/bin/vagrant box add http://box.shr.st --provider parallels"
  changed_when: false
  tags:
    - sharette

