---

- name: Ensure ejson key directory is present
  file:
    path: ~/.ejson/keys
    state: directory
    recurse: true
  tags:
    - sharette

- name: Setup ejson key directory
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export EJSON_KEYDIR="$HOME/.ejson/keys"'
  tags:
    - sharette

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_REGION="eu-west-1"'
  tags:
    - sharette

- name: Setup aws region
  lineinfile:
    dest: ~/.zshrc.local
    line: 'export AWS_DEFAULT_REGION="eu-west-1"'
  tags:
    - sharette

- name: Setup ssh_config
  template:
    src: ssh_config.j2
    dest: ~/.ssh/config
  tags:
    - sharette
