---


- name: Enable compta cron
  cron:
    name: daily compta
    minute: "32"
    hour: "17"
    job: "{{ home }}/Desktop/compta/daily.sh 2>&1 | tee -a {{ home }}/Desktop/compta/log/daily.log"
  tags:
    - settings

- name: "Check for updates automatically"
  shell: softwareupdate --schedule on
  changed_when: false
  become: true
  tags:
    - settings

- name: "Show the ~/Library folder"
  shell: chflags nohidden ~/Library
  changed_when: false
  tags:
    - settings

- name: "Disable local Time Machine backups (This can take up a ton of SSD space on <128GB SSDs)"
  shell: "tmutil disablelocal"
  changed_when: false
  become: true
  tags:
    - settings
